// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using TinyPermissionsLib.Sample.Data;

namespace TinyPermissionsLib.Sample.WebApi.Migrations
{
    [DbContext(typeof(DuckContext))]
    [Migration("20180121193941_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("TinyPermissionsLib.Sample.Data.Duck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("OwnerId");

                    b.Property<int>("Size");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Ducks");
                });

            modelBuilder.Entity("TinyPermissionsLib.Sample.Data.Function", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("TinyPermissionsLib.Sample.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TinyPermissionsLib.Sample.Data.UsersFunctions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FunctionId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersFunctions");
                });

            modelBuilder.Entity("TinyPermissionsLib.Sample.Data.Duck", b =>
                {
                    b.HasOne("TinyPermissionsLib.Sample.Data.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("TinyPermissionsLib.Sample.Data.UsersFunctions", b =>
                {
                    b.HasOne("TinyPermissionsLib.Sample.Data.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId");

                    b.HasOne("TinyPermissionsLib.Sample.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
